# Generated by Django 5.1.6 on 2025-02-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_hotel_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='yer',
            new_name='location',
        ),
    ]
