# Generated by Django 5.1.6 on 2025-02-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='rooms',
            new_name='room',
        ),
    ]
