# Generated by Django 5.1.6 on 2025-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_rename_rooms_reservations_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
