# Generated by Django 5.1.6 on 2025-02-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_reservations_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.rooms'),
        ),
    ]
