# Generated by Django 5.1.6 on 2025-02-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_reservations_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.rooms'),
        ),
    ]
