# Generated by Django 5.1.6 on 2025-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_reservations_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
